### ISSUE TITLE
Custom radio buttons: without JavaScript

### ISSUE THREAD

**Issue by michaelthorne** [putterschool/styleguide#33]
What you have looks great and works, but it would be cool to attempt it without requiring JavaScript to set the selected state of the radio button's label.

e.g. http://dabblet.com/gist/fca5b68b73b15aca87ac

That's a very simplistic example, so I don't know if it would work with the design of the radio buttons in this website. But it would be cool to try (and not rely on JS). :+1:

**Comment by laurenwaller** [comment]
Due to the :hankey: that is the Gravity Form radio button markup, decided to remove the custom radio buttons altogether.
