### ISSUE TITLE
Card position and z-index in patterns

### ISSUE THREAD

**Issue by michaelthorne** [putterschool/styleguide#35]
@laurenwaller cards look perfect on the home page, but there are a few issues in the patterns section of the style guide:

### Card link
![card-link](https://cloud.githubusercontent.com/assets/2629322/9953303/e75eb490-5ddf-11e5-96ab-8b6edac9a7bf.png)

### Card media
![card-img](https://cloud.githubusercontent.com/assets/2629322/9953323/0d87e86c-5de0-11e5-9b3a-4bc15f06704d.png)

### Card view code
![card-view-code](https://cloud.githubusercontent.com/assets/2629322/9953325/111a24d6-5de0-11e5-9d87-4d308560b0ef.png)

URL: http://s.wearenext.co.za/putter-school/styleguide/patterns.html

**Comment by michaelthorne** [comment]
### z-index

There is a section in [variables.less](https://github.com/putterschool/styleguide/blob/master/src/assets/less/generic/variables.less#L124-L151) where you can set the `z-index` as a variable for any object/pattern.

This helps you get an idea of the `z-index` of the other elements in use, so that you can set it appropriately (and make it easier to manage over time).

**Comment by michaelthorne** [comment]
### float

Wherever possible, I try to keep positioning stuff like [float](https://github.com/putterschool/styleguide/blob/master/src/assets/less/objects/card.less#L37) out of the object/pattern itself, and rather move it to a [wrapper](https://github.com/putterschool/styleguide/blob/master/src/assets/less/objects/card.less#L23).

That way you can use the single pattern anywhere, without enforcing any layout rules.

This will fix the issue with the **View Code** button.

**Comment by michaelthorne** [comment]
### Card media

I think you can remove `z-index: 1` from [.card__media](https://github.com/putterschool/styleguide/blob/master/src/assets/less/objects/card.less#L67)

Tested it on the home page and in the style guide.

Fixes the image (media) overlapping the style guide nav.

**Comment by michaelthorne** [comment]
@mieliep :arrow_up:

**Comment by laurenwaller** [comment]
@michaelthorne Thank you! I made some changes but not 100% sure how to incorporate the `card__link` z-index into variables.less?

**Comment by michaelthorne** [comment]
@laurenwaller check these two commits:

https://github.com/putterschool/styleguide/commit/f21159e8698862d156f4e73fb7835bcbeddb786b
https://github.com/putterschool/styleguide/commit/11dccbcf1a0ef95e1f56ac2633656a9ff7e5075e

I had to make an update to the style guide nav (need to do it in the boilerplate too).

Seems :100: now.

**Comment by laurenwaller** [comment]
@michaelthorne Rad thank you!! Will keep that all in mind for next time.
